In [1]:
import numpy as np

# Scalars

In [2]:
s = np.array(5)

In [3]:
s.shape

()

In [4]:
x = s + 3

In [5]:
x.shape

()

# Vectors

In [8]:
v = np.array([1,2,3])

In [10]:
v.shape

(3,)

In [11]:
x = v[1]

In [13]:
v[1:]

array([2, 3])

# Matrices

In [15]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [16]:
m.shape

(3, 3)

In [17]:
m[1][2]

6

# Tensors
### Tensors are just like vectors and matrices, but they can have more dimensions. For example, to create a 3x3x2x1 tensor

In [18]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [19]:
t.shape

(3, 3, 2, 1)

In [20]:
t[2][1][1][0]

16

# Changing shapes

In [23]:
v = np.array([1,2,3,4])

In [24]:
v.shape

(4,)

In [25]:
x = v.reshape(1,4)

In [26]:
x.shape

(1, 4)

In [27]:
x = v.reshape(4,1)

In [28]:
x.shape

(4, 1)

In [30]:
v[None, :]

array([[1, 2, 3, 4]])

In [31]:
v[:, None]

array([[1],
       [2],
       [3],
       [4]])

# Element-wise operations

In [ ]:
# Python way

In [52]:
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5

In [53]:
values

[6, 7, 8, 9, 10]

In [54]:
# Numpy way

In [55]:
values = [1,2,3,4,5]
values = np.array(values) + 5

In [56]:
values

array([ 6,  7,  8,  9, 10])

In [57]:
values += 5

In [58]:
values

array([11, 12, 13, 14, 15])

In [59]:
x = np.multiply(values, 5)

In [60]:
x

array([55, 60, 65, 70, 75])

In [61]:
x = x * 2

In [62]:
x

array([110, 120, 130, 140, 150])

In [63]:
# now every element in m is zero, no matter how many dimensions it has

In [64]:
m *= 0

In [65]:
m

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [66]:
m + 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# Element-wise Matrix Operations

In [68]:
a = np.array([[1,3],[5,7]])

In [69]:
a.shape

(2, 2)

In [70]:
b = np.array([[2,4],[5,7]])

In [71]:
b.shape

(2, 2)

In [72]:
a+b

array([[ 3,  7],
       [10, 14]])

In [73]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [74]:
a + c

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

# NumPy Matrix Multiplication

In [76]:
# Element-wise Multiplication
m = np.array([[1,2,3], [4,5,6]])

In [77]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
n = m * 0.25

In [79]:
n

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [80]:
m * n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [81]:
np.multiply(m, n)

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [82]:
# Matrix product

In [83]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [84]:
a.shape

(2, 4)

In [85]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [86]:
b.shape

(4, 3)

In [87]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [88]:
c = np.matmul(a,b)

In [89]:
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [90]:
c.shape

(2, 3)

In [91]:
# If your matrices have incompatible shapes, you'll get an error, like the following:
np.matmul(b, a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

# NumPy's dot function

In [92]:
a = np.array([[1,2],[3,4]])

In [93]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [94]:
# you can call `dot` directly on the `ndarray`
a.dot(a)

array([[ 7, 10],
       [15, 22]])

In [95]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])

# Transpose

In [97]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [98]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [100]:
m_t = m.T

### NumPy does this without actually moving any data in memory - it simply changes the way it indexes the original matrix - so it’s quite efficient. However, that also means you need to be careful with how you modify objects, because they are sharing the same data.

In [101]:
m_t[3][1] = 200

In [102]:
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [103]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

In [105]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])

In [106]:
inputs.shape

(1, 4)

In [108]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

In [109]:
weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [110]:
weights.shape

(3, 4)

In [111]:
np.matmul(inputs, weights)

ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [112]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [113]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

### The two answers are transposes of each other, so which multiplication you use really just depends on the shape you want for the output.