In [1]:
import tensorflow as tf
import numpy as np

/Users/yunsungsong/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.__version__

'1.11.0'

In [3]:
a = tf.add(2,2)

In [4]:
sess = tf.Session()

In [5]:
sess.run(a)

4

## Tensorflow로 데이터를 표현하는 법
tf.constant = 상수를 생성
tf.Variable = 변수를 생성
Placeholder = 특정한 데이터 센서를 표현하는 것이 아닌 데이터가 포함되는 공간 (그릇과 같은)
dtype, shape, name을 전달 인자로 가지고 있음
sess.run 을 실행하기전에 feed_dict에 넣을 dictionary를 구성하고, 실행할 때 입력값으로 사용

In [6]:
# 1. 그래프빌드

node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(5.0, tf.float32)
node3 = tf.add(node1, node2)
# 2. 실행
sess = tf.Session()
print(sess.run([node1, node2, node3]))

[3.0, 5.0, 8.0]


In [7]:
ph1 = tf.placeholder(tf.float32)

In [8]:
ph2 = tf.placeholder(tf.float32)

In [9]:
adder = ph1 + ph2

print(sess.run(adder, 
               feed_dict={ph1: [[3,4,5],[1,2,3]], 
                          ph2: [[4,5,6], [5,6,7]]}))

[[ 7.  9. 11.]
 [ 6.  8. 10.]]


In [10]:
v1 = tf.Variable(tf.random_normal([10,10], stddev=0.35))
v2 = tf.Variable(tf.random_normal([10,10], stddev=0.35))
sess.run(tf.global_variables_initializer())

In [11]:
sess = tf.InteractiveSession() #디버깅
t = tf.constant([[1,2,3,4], [1,2,3,4]])
print (tf.shape(t).eval())

[2 4]


In [12]:
mat1 = tf.constant([[1,2],[3,4]])
mat2 = tf.constant([[1],[2]])

print(tf.shape(mat1).eval())
print(tf.shape(mat2).eval())
print((mat1 * mat2).eval())

[2 2]
[2 1]
[[1 2]
 [6 8]]


In [13]:
x = [[1.,2.],
     [3.,4.]]
tf.reduce_mean(x).eval()

2.5

In [14]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [15]:
tf.reduce_mean(x, axis=0).eval()

#axis에 -1을 넣으면 가장 안쪽값이 계산

array([2., 3.], dtype=float32)

In [16]:
tf.reduce_sum(x, axis=1).eval()

array([3., 7.], dtype=float32)

In [17]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [18]:
x = [[0,1,2],[3,4,5]]

In [19]:
tf.argmax(x, axis=0).eval() 
# 아래행이 다 크니까 111 이 나온거

array([1, 1, 1])

In [20]:
tf.argmax(x, axis=1).eval() 

array([2, 2])

In [21]:
tf.argmax(x, axis=-1).eval() 

array([2, 2])

In [22]:
x = [1,2,3,4,5,6,7,8,9]
tf.reshape(x, [3,3]).eval()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [23]:
t= tf.one_hot([[0],[1],[2],[3]], depth = 4).eval()

In [24]:
t= tf.reshape(t, [-1,4]).eval()
print(t)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
tf.cast([1,3,4,5,5.5], tf.int32).eval()

array([1, 3, 4, 5, 5], dtype=int32)

In [26]:
x = [1,4]
y = [2,5]
z = [3,6]
tf.stack([x,y,z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [27]:
x = [[1,2,3],[4,5,6],[7,8,9]]
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [28]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)