In [8]:
import tensorflow as tf
import numpy as np

In [12]:
x = np.array([[1,2,3], [4,5,6]])
print(x.shape)
np.ndim(x)

(2, 3)


2

In [13]:
a = np.zeros((10,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
a = np.ones((10,10))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
c = np.full((3,3,3),7)
print(c)

[[[7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]]]


In [18]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
np.random.random((3,3))

array([[0.28106014, 0.77048882, 0.37805174],
       [0.13812587, 0.5258716 , 0.83063868],
       [0.38057997, 0.00236744, 0.10048138]])

In [20]:
# tf.random_normal
# tf.random_uniform
# 제일 많이 쓰는 랜덤종류들

In [22]:
np.linspace(0,20,40) #0~20까지의 숫자를 40개 칸에 입력

array([ 0.        ,  0.51282051,  1.02564103,  1.53846154,  2.05128205,
        2.56410256,  3.07692308,  3.58974359,  4.1025641 ,  4.61538462,
        5.12820513,  5.64102564,  6.15384615,  6.66666667,  7.17948718,
        7.69230769,  8.20512821,  8.71794872,  9.23076923,  9.74358974,
       10.25641026, 10.76923077, 11.28205128, 11.79487179, 12.30769231,
       12.82051282, 13.33333333, 13.84615385, 14.35897436, 14.87179487,
       15.38461538, 15.8974359 , 16.41025641, 16.92307692, 17.43589744,
       17.94871795, 18.46153846, 18.97435897, 19.48717949, 20.        ])

In [23]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [24]:
print(x[:2, 1:])

[[2 3]
 [5 6]]


In [25]:
x = np.array([1,2,3,4,5,6,7,8])

In [27]:
print(x[2:6])
print(x[:])
print(x) 
# : 와 x로 그냥 불러왔을때는 서로 다른 값이다. 절대로 같은게 아니기 때문에 x전체의 데이터를 불러오고자 하면 
# x[:]으로 입력한다.

[3 4 5 6]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [28]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [29]:
print(x[:,2:])

[[3]
 [6]
 [9]]


In [38]:
arr = np.arange(12).reshape(4,3)
row_mean = arr.mean(axis=1).reshape(4,1)

In [40]:
print(row_mean)

[[ 1.]
 [ 4.]
 [ 7.]
 [10.]]


In [41]:
arr -row_mean

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])